Repository epiverse-trace/ColOpenData, pull requests merged in 2024-02, with the labels that each got.

#35 Dev consult module
  CITATION.cff
  DESCRIPTION
  NAMESPACE
  R/documentation.R
  R/download.R
  R/download_climate.R
  README.md
  inst/WORDLIST
  inst/extdata/config.yaml
  man/aggregate.Rd
  man/dictionary.Rd
  man/download_climate.Rd
  man/download_climate_geom.Rd
  man/group_stations.Rd
  man/list_datasets.Rd
  man/retrieve_climate_data.Rd
  man/retrieve_stations_data.Rd
  man/retrieve_table.Rd
  man/summarise.Rd
  tests/testthat/test-documentation.R
  tests/testthat/test-download_climate.R
  vignettes/climate_data.Rmd
  vignettes/documentation_and_dictionaries.Rmd
  vignettes/geospatial_data.Rmd
Labels: enhancement

#37 Update demographic sources
  CITATION.cff
  DESCRIPTION
  R/download.R
  R/download_demographic.R
  inst/extdata/config.yaml
  man/download_demographic.Rd
  man/retrieve_excel.Rd
  man/retrieve_table.Rd
  tests/testthat/test-download_demographic.R
Labels: enhancement

#46 Dev update climate vignette
  DESCRIPTION
  NAMESPACE
  R/documentation.R
  R/download.R
  R/download_climate.R
  R/download_demographic.R
  R/download_geospatial.R
  inst/WORDLIST
  man/download_climate.Rd
  man/download_climate_data.Rd
  man/download_climate_geom.Rd
  man/list_datasets.Rd
  man/retrieve_demographic_dataset.Rd
  man/retrieve_geospatial_dataset.Rd
  man/retrieve_stations_data.Rd
  man/retrieve_zip.Rd
  man/stations_in_roi.Rd
  tests/testthat/test-download_climate.R
  vignettes/climate_data.Rmd
  vignettes/documentation_and_dictionaries.Rmd
Labels: documentation, enhancement

#38 Dev update geospatial vignette
  R/dengue_2018.R
  data/dengue_2018.rda
  inst/WORDLIST
  man/dengue_2018.Rd
  vignettes/climate_data.Rmd
  vignettes/documentation_and_dictionaries.Rmd
  vignettes/geospatial_data.Rmd
Labels: documentation, enhancement

#45 Dev fix download
  R/dengue_2018.R
  data/dengue_2018.rda
  inst/WORDLIST
  man/dengue_2018.Rd
  vignettes/climate_data.Rmd
  vignettes/documentation_and_dictionaries.Rmd
  vignettes/geospatial_data.Rmd
Labels: enhancement

#50 Dev enhance config
  DESCRIPTION
  R/documentation.R
  R/download.R
  R/download_demographic.R
  R/download_geospatial.R
  inst/extdata/config.yaml
  man/download_demographic.Rd
  man/download_geospatial.Rd
  man/retrieve_path.Rd
  man/retrieve_table.Rd
  man/retrieve_value_key.Rd
  tests/testthat/test-documentation.R
Labels: documentation, enhancement

#54 Dev fix vignettes
  CITATION.cff
  DESCRIPTION
  NAMESPACE
  R/documentation.R
  R/download_climate.R
  README.Rmd
  README.md
  man/download_climate_stations.Rd
  tests/testthat/test-download_climate.R
  vignettes/climate_data.Rmd
  vignettes/documentation_and_dictionaries.Rmd
  vignettes/geospatial_data.Rmd
Labels: documentation, enhancement

#53 Dev demographic vigennete moreexamples
  vignettes/demographic_data.Rmd
Labels: documentation

#65 Dev download geospatial
  R/download.R
  R/download_climate.R
  R/download_demographic.R
  R/download_geospatial.R
  inst/extdata/config.yaml
  man/download_demographic.Rd
  man/download_geospatial.Rd
  man/retrieve_zip.Rd
  tests/testthat/test-documentation.R
  tests/testthat/test-download_climate.R
  tests/testthat/test-download_geospatial.R
  vignettes/geospatial_data.Rmd
Labels: enhancement

#66 Dev fix review details
  CITATION.cff
  DESCRIPTION
  R/dev-utils.R
  R/documentation.R
Labels: review
